module.exports = {
  Role: require('./Role'),
  Year: require('./Year'),
  Sede: require('./Sede'),
  Course: require('./Course'),
  TypeTask: require('./TypeTask'),
  RolComision: require('./RolComision'),
  User: require('./User'),
  CourseSedeAssignment: require('./CourseSedeAssignment'),
  CourseAssignment: require('./CourseAssignment'),
  Task: require('./Task'),
  TimelineEvento: require('./TimelineEvento'),
  Comment: require('./Comment'),
  CommentVersion: require('./CommentVersion'),
  TaskSubmission: require('./TaskSubmission'),
  ThesisSubmission: require('./ThesisSubmission'),
  GroupComision: require('./GroupComision'),
  Comision: require('./Comision'),
  StudentComision: require('./StudentComision'),
  RevisionThesis: require('./RevisionThesis'),
  AssignedReview: require('./AssignedReview'),
  ApprovalThesis: require('./ApprovalThesis'),
  CommentRevision: require('./CommentRevision'),
  Notification: require('./Notification'),
  AppLog: require('./AppLog')
};
